<%@ Page Title="" Language="C#" MasterPageFile="~/admin_page.master" AutoEventWireup="true" CodeFile="Default5.aspx.cs" Inherits="Default5" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<br />
<div  style = "width=100%; margin-left:40px; margin-right:40px;">

    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
        DataSourceID="SqlDataSource1" AutoGenerateEditButton="True" 
        CellPadding="10" ForeColor="Black" AutoGenerateDeleteButton="True" 
         BackColor="#CCCCCC" BorderColor="#999999" 
        BorderStyle="Solid" BorderWidth="3px" CaptionAlign="Top" CellSpacing="5" 
        Height="100%" HorizontalAlign="Center" Width="100%" 
        AllowPaging="True" AutoGenerateSelectButton="True" >
        <Columns>
           <asp:BoundField DataField="game_id" HeaderText="game_id" 
                SortExpression="game_id" > 
            </asp:BoundField>
            <asp:BoundField DataField="game_name" HeaderText="game_name" 
                SortExpression="game_name" >
            </asp:BoundField>
        </Columns>
        <FooterStyle BackColor="#CCCCCC" />
        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" 
            HorizontalAlign="Center" VerticalAlign="Middle" />
        <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
        <RowStyle BackColor="White" />
        <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#F1F1F1" />
        <SortedAscendingHeaderStyle BackColor="#808080" />
        <SortedDescendingCellStyle BackColor="#CAC9C9" />
        <SortedDescendingHeaderStyle BackColor="#383838" />
    </asp:GridView>



    <br />



    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:mydbConnectionString %>" 
        
        SelectCommand="SELECT [game_id], [game_name] FROM [carts_db] WHERE (([username] = @username) AND ([phone_no] = @phone_no))" >
        <SelectParameters>
            <asp:SessionParameter Name="username" SessionField="login_user" Type="String" />
            <asp:SessionParameter Name="phone_no" SessionField="phoneno" Type="String" />
        </SelectParameters>
   
    </asp:SqlDataSource>
<!-- for delete command add 'DataKeyNames="game_id" in asp:GridView tag --> 


    <br />
    <br />



</div>


</asp:Content>

